# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Boxes(_IBM):
    _type = "boxes"
    _icon_dir = "resources/ibm/boxes"


class Classicinfrastructure(_Boxes):
    _icon = "classicinfrastructure.png"


class Cloud(_Boxes):
    _icon = "cloud.png"


class Enterprisenetworks(_Boxes):
    _icon = "enterprisenetworks.png"


class Publicnetwork(_Boxes):
    _icon = "publicnetwork.png"


class Region(_Boxes):
    _icon = "region.png"


class Subnetacl(_Boxes):
    _icon = "subnetACL.png"


class Vpc(_Boxes):
    _icon = "vpc.png"


class Zone(_Boxes):
    _icon = "zone.png"


# Aliases
