# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Vpc(_IBM):
    _type = "vpc"
    _icon_dir = "resources/ibm/vpc"


class BareMetalServer(_Vpc):
    _icon = "bare-metal-server.png"


class BlockStorage(_Vpc):
    _icon = "block-storage.png"


class Bridge(_Vpc):
    _icon = "bridge.png"


class CloudServices(_Vpc):
    _icon = "cloud-services.png"


class Datacenter(_Vpc):
    _icon = "datacenter.png"


class DirectLink(_Vpc):
    _icon = "direct-link.png"


class Enterprise(_Vpc):
    _icon = "enterprise.png"


class FloatingIp(_Vpc):
    _icon = "floating-ip.png"


class ImageService(_Vpc):
    _icon = "image-service.png"


class Instance(_Vpc):
    _icon = "instance.png"


class InternetServices(_Vpc):
    _icon = "internet-services.png"


class Internet(_Vpc):
    _icon = "internet.png"


class Key(_Vpc):
    _icon = "key.png"


class LoadBalancerListener(_Vpc):
    _icon = "load-balancer-listener.png"


class LoadBalancerPool(_Vpc):
    _icon = "load-balancer-pool.png"


class LoadBalancer(_Vpc):
    _icon = "load-balancer.png"


class ObjectStorage(_Vpc):
    _icon = "object-storage.png"


class PowerInstance(_Vpc):
    _icon = "power-instance.png"


class PublicGateway(_Vpc):
    _icon = "public-gateway.png"


class Router(_Vpc):
    _icon = "router.png"


class Rules(_Vpc):
    _icon = "rules.png"


class TransitGateway(_Vpc):
    _icon = "transit-gateway.png"


class VpnConnection(_Vpc):
    _icon = "vpn-connection.png"


class VpnGateway(_Vpc):
    _icon = "vpn-gateway.png"


class VpnPolicy(_Vpc):
    _icon = "vpn-policy.png"


# Aliases
